services:
  db:
    container_name: market-place-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
  web:
    container_name: market-place-web
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
